#!/bin/bash
filename="$1"
option1="$2"
if [[ $filename == "" ]]; then
  read filename
fi
if [[ $option1 == "-debug" ]]; then
  debug=$"true"
else
  debug=$"false"
fi
if [[ $option1 == "-min" ]]; then
  mode=$"min"
else
  mode=$"reg"
fi
declare -a lines
declare -a colors
declare -a catoponents
declare -a catos
declare -a kitname
declare -a kitdata
# add colors!
syscolor=$"\e[1;36m"
colors+=("\e[0m"); #1 or default
colors+=("\e[0;30m"); #2 or black
colors+=("\e[0;31m"); #2 or red
colors+=("\e[0;33m"); #3 or yellow
colors+=("\e[0;32m"); #4 or green
colors+=("\e[0;32m"); #5 or purple
colors+=("\e[0;34m"); #6 or blue
declare -i color
color=$"1"
version=$"Dev0.1.0-pre"
sed -i "s/^Version:.*/Version: $version/" ./catoponents/project.catofig
CONPON=./catoponents/catoponents.catofig
PROG=./catoponents/project.catofig
if [ -d "./catoponents" ]; then
if [ -f "$CONPON" ]; then
    tmp=`sed -n '3p' $PROG`
    mainkit=`grep -oP '(?<=:).*?(?=>)' <<< "$tmp"`
    echo "cato project ready to run"
    timestamp=`date`
    echo "project prepared @ $timestamp" >> ./catoponents/log.catd
else 
    error=$"Catoponet file not found!";
    timestamp=`date`
    echo "project failed @ $timestamp Reason: $error" >> ./catoponents/log.catd
    echo $error
fi
else
  if ./pur; then
    ./pur init $filename $version
  else
    echo "INSTALL PUR! *pur not found"
    exit;
  fi
fi
error=$"No errors code executed!";
if [[ $filename == *".cato"* ]]; then
  mkdir ./catoponents/runtime
if test -f "$filename"; then
  if [[ $mode == "reg" ]]; then
      echo -e "${syscolor}Preparing $filename . . ."
      echo "Runnig CatoScript version $version" >> ./catoponents/runtime/debuglog.catd
      echo "Preping $filename for runtime" >> ./catoponents/runtime/debuglog.catd
    fi
    while IFS= read -r line
    do
      lines+=("$line");
    done < "$filename";
    lines+=("$line");
    foo=0
    len=${#lines[@]}
    while [ $foo != $len ]; do
      if [[ ${lines[$foo]} == *"@kitten"* ]]; then
        kitten=`grep -oP '(?<=<).*?(?=>)' <<< "${lines[$foo]}"`
        echo "kitten found!"
        foo=$(( $foo + 1 ))
        while [[ ${lines[$foo]} != *"}"* ]]; do
          echo "${lines[$foo]}"
          echo "${lines[$foo]}" >> ./catoponents/runtime/$kitten.catokit
          foo=$(( $foo + 1 ))
        done
        echo "Class $kitten created" >> ./catoponents/runtime/debuglog.catd
      fi
      foo=$(( $foo + 1 ))
    done
  else
    error=$"${syscolor}This file doesn't exsit"
    timestamp=`date`
    echo "project failed @ $timestamp Reason: $error" >> ./catoponents/log.catd
    echo -e "${syscolor}$error"
    sleep 2
    exit;  
  fi
  else
   error=$"${syscolor}This file is not a cato script file"
    echo -e "${syscolor}$error"
    sleep 2
    exit; 
fi

echo -e "${syscolor}Running $filename"
#code to interput the cato file
while IFS= read -r line
    do
      catlines+=("$line");
    done < "./catoponents/runtime/$mainkit.catokit";
    catlines+=("$line");
    acvlines=${#catlines[@]}
    declare -i ll
    ll=`expr $acvlines+1`
    foo=0
if [ -f './catoponents/runtime/$mainkit.catokit' ]; then
  timestamp=`date`
  echo "Project Failed @ $timestamp Reason:ERROR-100 Main class $mainkit not found" >> ./catoponents/log.catd
  echo -e "${colors[2]} ERROR-100! check logs"
  rm -r ./catoponents/runtime
  exit;
fi
foo=0
while [[ $foo != $acvlines ]]; do
  foo=$(( $foo + 1 ))
  if [[ ${catlines[$foo]} == *"%"* || ${catlines[$foo]} == "" ]]; then
    echo "Commented line" >> ./catoponents/runtime/debuglog.catd
  elif [[ ${catlines[$foo]} == *"console.write"* ]]; then
    tmp=$(echo ${catlines[$foo]} | cut -d'"' -f 2)
    echo $tmp
    echo "Wrote $tmp to console" >> ./catoponents/runtime/debuglog.catd
  elif [[ ${catlines[$foo]} == *"debug.write"* ]]; then
    tmp=$(echo ${catlines[$foo]} | cut -d'"' -f 2)
    echo "$filename | $tmp" >> ./catoponents/runtime/debuglog.catd
  else
    foo=$(( $foo + 1 ))
    echo "Project Failed @ $timestamp Reason:ERROR-101 invaild method on line $foo inside the main class| ${catlines[$foo]}" >> ./catoponents/log.catd
    echo -e "${colors[2]} ERROR-101! check logs"
    rm -r ./catoponents/runtime
    exit;
  fi
done
#end code
if [[ $debug == "true" ]]; then
  echo -e "${syscolor}$error"
  echo -e "${syscolor}$filename has finshed running!"
  timestamp=`date`
  echo "debug log for $timestamp | $dblog" >> ./catoponents/log.catd
  echo "$foo lines ran" >> ./catoponents/log.catd
 while IFS= read -r line
    do
      echo "$line" >> ./catoponents/log.catd
    done < "./catoponents/runtime/debuglog.catd";
     echo -e "${syscolor}Debug Log saved to log file"
else
  error="${syscolor}$error | Invaild debug vaule set"
fi
if [[ $mode == "reg" ]]; then
  echo -e "${syscolor}press enter to end cato session!"
  read foo
fi
timestamp=`date`
echo "project ran @ $timestamp using CatoScript:$version" >> ./catoponents/log.catd
rm -r ./catoponents/runtime